### ISSUE TITLE
Remove unnecessary pygame imports

### ISSUE THREAD

**Issue by Kiyotoko** [seekers-dev/seekers-py#53]
Currently, pygame is required to run for the client only. There is no reason why the client needs render support. It only should be required for ``run_seekers.py``.

**Comment by Belissimo-T** [comment]
+1, I think we once fixed this issue at the LSGM Mathecamp 2022 but didn't push it.

**Comment by Supergecki** [comment]
Which file are we talking about here? I first thought you meant `run_client.py` but there is no import of pygame and I couldn't even find one in the file's history.

**Comment by Kiyotoko** [comment]
I guess that ``run_seekers.py`` loads the seekers module, which loads the ``__init__.py`` file, which imports ``pygame``.

**Comment by Belissimo-T** [comment]
@Kiyotoko It's about `run_client.py`

**Comment by Kiyotoko** [comment]
> @Kiyotoko It's about `run_client.py`

Yes, but it is the same for ``run_client.py`` and ``run_seekers.py``. Of course this is only the case if I unterstand python modules correctly.

**Comment by Supergecki** [comment]
Okay, I might have found what was causing this.

`run_client.py` imports `seekers.grpc`, which in itself is fine since it needs the GRPC functions from there.
But in order to import this `grpc` part of the module, the code in `seekers`'s `__init__.py` file is executed first, which imports `pygame` for the clocks to be set up.

The problem now is that this seems to be a matter of directory and dependency design. `run_client.py` _definitely_ needs the GRPC functions, but these are "locked" inside the `seekers` folder which, when imported, automatically gives us `pygame`.
I don't think there is a solution solely based on changing our code.

**Comment by Kiyotoko** [comment]
Why does `__init__.py` needs to import `pygame`? Can we not simply remove it?

**Comment by Supergecki** [comment]
`__init__.py` currently contains the `mainloop` method of the `SeekersGame` class. If I see it correctly, `pygame` is used for two things:

1. Initiating and running the `pygame` clock. This is needed to have the game running at a constant rate of FPS.
2. Handling incoming `pygame` events. Currently, only the `QUIT` event is being handled, causing the mainloop to stop running (the same way as the game logic does when the maximum number of ticks is reached).

I can imagine that the second thing would be a bit easier to outsource than the first one. Some module has to handle it, and currently, `__init__.py` does that.

**Comment by Belissimo-T** [comment]
@Supergecki Please don't think so hard about this 😭, I will fix it.

**Comment by Supergecki** [comment]
Okay, sorry then 😅
